ci: add test report
For
https://github.com/numberscope/frontscope/pull/212#issuecomment-1329745772.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,4 +1,4 @@
-name: Continuous integration
+name: 'CI'
 on: pull_request
 jobs:
     ci:
@@ -18,4 +18,9 @@ jobs:
             - name: Lint
               run: npm run lint:check
             - name: Run tests
-              run: npm run test:unit
+              run: npm run test:ci:unit
+            - uses: actions/upload-artifact@v2 # upload test results
+              if: success() || failure() # run this step even if previous step failed
+              with:
+                  name: test-results
+                  path: test-report.xml
